### ISSUE TITLE
use angular router to resolve data before it active corresponding component

### ISSUE THREAD

**Issue by Shanfang** [Shanfang/SmartNote#13]

**Comment by Shanfang** [comment]
notes component is able to use resolved data  since commit c9b55a3a3178981e6e8298e268725aa7be3fd9f6

**Comment by Shanfang** [comment]
I reopened this issue because other components in our application have not been updated to use resolved data.

**Comment by CindyHXH** [comment]
Slove it with commit Ca8e3755a8c2c07f967c6d8f97a612af7f03e09c4.

**Comment by CindyHXH** [comment]
Solve it with commit a8e3755a8c2c07f967c6d8f97a612af7f03e09c4.
