### ISSUE TITLE
Integrate login authentication 

### ISSUE THREAD

**Issue by CindyHXH** [Shanfang/SmartNote#23]
Integrate login authentication for user account management.

**Comment by jeness** [comment]
- [x]  authentication via /server/src/user.js
- [x]  when users pass authentication, navigate to localhost:4200/addLinknote
- [x]  authentication via mongodb connection
- [x]  port conflicts between localhost:3000 and localhost:4200 at the /todos URL

**Comment by CindyHXH** [comment]
Fix login/sign out functions with commit 651f4c1dd0f9f7a1a268978613fb586e034ccc23.
