### ISSUE TITLE
End-to-end Test

### ISSUE THREAD

**Issue by CindyHXH** [Shanfang/SmartNote#24]
Implement more comprehensive end-to-end test:
- [x] Tag
- [x] Login/Sign out
- [x] home page
- [x] About
- [x] URL note
- [x] add note
- [x] markdown note
- [x] archieve note
- [x] view note
- [x] delete note
- [x] modify note 
- [x] search note

**Comment by Shanfang** [comment]
login, about, URL note have been well tested with protractor.
