### ISSUE TITLE
Manage deleted notes

### ISSUE THREAD

**Issue by Shanfang** [Shanfang/SmartNote#6]

**Comment by CindyHXH** [comment]
Manage deleted notes designed to 

- [x] After save a markdown note, view created note index

- [x] Choose to modify, or delete note.

- [x] Notes deleted cannot be viewed on Archived notes.

**Comment by CindyHXH** [comment]
Complete it with commit 6fe761f9b6ddfaf43d04f387cb0fd1e3031d485a.
